- name: Copy file to remote server
  hosts: samplenode3
  become: true
  vars:
    local_file_path: "/home/devopsadmin/workspace/fin_try"
    remote_file_path: "/home/devopsadmin"
  tasks:
    - name: Copy file
      copy:
        src: "{{ local_file_path }}"
        dest: "{{ remote_file_path }}"
