apiVersion: apps/v1
kind: Deployment
metadata:
  name: csark-insudepoansible-deploy
  labels:
    app: csark-insudepoansible-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csark-insudepoansible-deploy
  template:
    metadata:
      labels:
        app: csark-insudepoansible-deploy
    spec:
      containers:
      - name: csark-insudepoansible-container
        image: csark/insurance-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: csark-insudepoansible-np-service
  labels:
    app: csark-insudepoansible-deploy
spec:
  selector:
    app: csark-insudepoansible-deploy

  type: NodePort
  ports:
  - nodePort: 31600
    port: 8081
    targetPort: 8081
